name: my_first_flutter_app
description: "A restaurant reservation app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  









  # Core
  flutter_riverpod: ^3.0.3
  intl: ^0.20.2


  js: ^0.7.2
  
  # UI Components 
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1 
  flutter_slidable: ^4.0.3
  table_calendar: ^3.0.9
  flutter_spinkit: ^5.2.1
  
  
  
  

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  cloud_functions: ^6.0.4

  image_picker: ^1.1.2

  
  # State Management
  provider: ^6.1.1
  
  # Development Tools
  device_preview: ^1.3.1
  
  # Validation
  email_validator: ^3.0.0
  
  # Navigation
  go_router: ^17.0.0
  get_it: ^9.1.1
  
  # Form Handling
  intl_phone_field: ^3.2.0
  
  # Local Storage 
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  path: ^1.9.1
  
  # Location (تم تحديث geolocator)
  geolocator: ^14.0.2
  google_maps_flutter: ^2.5.1
  
 
  
  # Notifications
  flutter_local_notifications: ^19.5.0
  
  # Utils
  uuid: ^4.2.2
  equatable: ^2.0.5
  logger: ^2.0.2
  url_launcher: ^6.3.2
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.2
  json_rpc_2: ^4.0.0
  stack_trace: ^1.12.1
  web: ^1.1.1
  fluttertoast: ^9.0.0
  googleapis_auth: ^1.6.0
  flutter_bloc: ^8.1.3


 

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  path_provider_platform_interface: ^2.1.2
  
flutter:
  uses-material-design: true


  assets:
     - assets/
     - assets/firebase/

